### ISSUE TITLE
We might need to compress simulation outputs somewhere

### ISSUE THREAD

**Issue by nickeubank** [nickeubank/us_ensembles#12]
This is a LOT of data. I can store it on the cluster without a problem, but moving it around after is gonna be a real pain. Can we either zip before save, or store in a format that has in-built compression (e.g. HDF5)?

**Comment by nickeubank** [comment]
Like: each state-run is ~4 gigs. times 50 states, times 3 chains per state.... 

Also, the flips_[num].json appear cumulative (judging by size)  --  can we just keep the last flip-list if so?

(Mostly the flips JSON files, which are about a half-gig a piece). 

![image](https://user-images.githubusercontent.com/9683693/72001227-fb970500-3212-11ea-8952-847505b0fcfe.png)

**Comment by nickeubank** [comment]
Ooooooh... the writing out isn't writing and dumping memory; the memory footprint is still cumulative. That's why my memory estimates were off.

Should we be doing that? Writing out each 10,000 flips and then deleting them from memory?

**Comment by drdeford** [comment]
Oops! They were supposed to be but I forgot to reset the flips dictionary after writing. The rest of them should be deleting after writing.

**Comment by nickeubank** [comment]
ok, will tweak. 

God bless Duke: even asking for 20gb per core, I get 150 cores instantly. :) Still, don't want the disk writing. Will fix.

**Comment by drdeford** [comment]
For compression overall, switching to hdf5 seems like a good idea. Everything except for the assignments (which are int to int dicts) is just lists or arrays of real numbers so the current csv writing is just for convenience.

**Comment by nickeubank** [comment]
Would you confirm the commit now referenced in this issue is all we needed?

The flips were the only thing creating a big footprint. This should basically fix the problem.

**Comment by drdeford** [comment]
Yes, that is the one I missed :)
