### ISSUE TITLE
Results on dropbox

### ISSUE THREAD

**Issue by nickeubank** [nickeubank/us_ensembles#13]
State 01 didn't have any memory problems, so I'm dropping all three (successful) runs into a dropbox folder I'll share with you Daryl so you can start prototyping code if you'd like (since apparently you like distractions? :)).

**Comment by drdeford** [comment]
Great! I'll get a first draft uploaded this evening.

**Comment by nickeubank** [comment]
Ok! New results will have cumulative JSONs, so bear that in mind!
