### ISSUE TITLE
Dislocation for Ensembles

### ISSUE THREAD

**Issue by drdeford** [nickeubank/us_ensembles#14]
Now that we have a few ensembles ready to analyze we can also start getting the code ready to compute dislocation scores on everything. I'll put together an outline tomorrow based on the approach in the previous repo. 

We had talked previously about trying to wrap that up as a package, which will require a little bit of thinking about inputs too. Particularly how the designated points should be represented.

**Comment by nickeubank** [comment]
Great. 

I’m open to going package first, but for 2008 we have all the nearest neighbors calculated already, so we don’t NEED to write code for that yet. Maybe we should just use the 2008 voter points we have first for analysis and put packaging lower in the queue?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nickeubank** [comment]
Also I did some very basic tinkering on an API: https://github.com/nickeubank/partisan_dislocation/

**Comment by drdeford** [comment]
Good point about relative priorities! I think using the previously calculated points for now makes lots of sense.

**Comment by drdeford** [comment]
The skeleton for rerunning the chain to compute new things is on dropbox now. We will need the original jsons to build the starting partitions, which puts us back in data transfer/storage problem land.

**Comment by nickeubank** [comment]
> The skeleton for rerunning the chain to compute new things is on dropbox now. We will need the original jsons to build the starting partitions, which puts us back in data transfer/storage problem land.

OK, missed something -- why do we need to rerun things? Don't the chains I'm running now meet all our district simulation needs?

(Side note: down to 22 still running...)

**Comment by drdeford** [comment]
Rerunning is probably bad verbiage on my part - we didn't compute disclocation scores on the first past through, so we have to ``touch'' all the plans again to do the measurements. Since we are rebuilding the partitions from the flip in order to do the measurements I have been thinking about it as rerunning but no new plans need to be generated or anything like that.

**Comment by nickeubank** [comment]
OH! got it. 

How about this for storage / git interaction: 

We only have the one dropbox folder (`dislocation_intermediate_files`), and when we want to access it from a script we call a variable called something like `dropbox_dir`, which we define at the top of each script (for easy changing if we use one another's scripts)?

Or we could try and establish a common relative path. My dropbox, with respect to my `dislocation_and_simulated_districts/10_code` would be: `../../../dropbox/dislocation_intermediate_files`, but I can also remove one of those "ups" pretty easily if needed.

**Comment by drdeford** [comment]
Probably easier to have a dropbox_dir at the top of the scripts. In general, I sort of prefer relative paths but my current dropbox->ubuntu setup would make that pretty difficult.

**Comment by nickeubank** [comment]
Of course you use ubuntu. I'll admit I was perplexed when your screenshot *looked* like windows not mac; but of course it wasn't windows, it was linux. 

Why is this hard on ubuntu? Does it not just exist like a directory the way it does on mac or windows? Even if the folder lives in a weird place, presumably you could add a `symlink` in a more convenient location, no?

**Comment by drdeford** [comment]
Some of the screenshots might have been windows from my laptop :) but my desktop ubuntu is the problem. I just tried it out and a symlink seems to work fine. My concern was that the DropBox location is on a separate hard drive that isn't always mounted. However, if I were going to use this then obviously I would mount it first...

**Comment by nickeubank** [comment]
and if not presumably you'd get an informative error, no?

I'm up for giving it a shot. Easy to reverse if needed. Wanna try assuming 3 ups (`../../../dropbox/dislocation_intermediate_files`)?

**Comment by drdeford** [comment]
That seems to work for me!

**Comment by nickeubank** [comment]
Great, let's give it a shot!

Great Re: CA btw. I think I'll hold off setting things running till we have the seeds we want for both FL and CA. I figure when the current run ends I can pull down all the other states and we can develop code; then I can get FL and CA running together when ready, and add when done.

**Comment by drdeford** [comment]
I shifted the three files over from dropbox to github with the new relative paths and it all seems to work great. 

The remaining CA 2% seed is uploaded, so those should all be ok now.

**Comment by nickeubank** [comment]
Great! Did we do updated FL too? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by drdeford** [comment]
Yeah, the FL ones are there too - CA was just slower since it has more districts.

**Comment by nickeubank** [comment]
Great will get those up and running! I will also get all the completed runs on the dropbox tonight or tomorrow morning! Couple still running...

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by drdeford** [comment]
They are named precicnt_graphs_*_new2seed*.json so as to not overwrite the previous ones.

**Comment by nickeubank** [comment]
OK -- I *am* gonna overwrite the old names in my next commit (which will be flagged on this issue) so they code all looks the same. But we can always checkout the old ones using the commit before this if needed!
