### ISSUE TITLE
repo organization

### ISSUE THREAD

**Issue by nickeubank** [nickeubank/us_ensembles#16]
OK, in an effort to organize things well, I've ended up creating a bit of an explosion of repos, so I wanted to touch base and see if people were ok with the following organization: 

- [us_ensembles](https://github.com/nickeubank/us_ensembles): Public repo with all the district ensembles and code (which may be of use to other people doing gerrymandering work)
- [partian_dislocation](https://github.com/nickeubank/partisan_dislocation/): Public repo where we can eventually house a package for doing this stuff. 
- [dislocation_and_simulated_districts](https://github.com/nickeubank/dislocation_and_simulated_districts/) Private repo that *was* for the new paper we were gonna write, but I think should now be for this paper. Given that, I'll integrate all the code and data currently used to write what we've already written, and we can add the new analysis code we're developing there? I'll keep a version of some things (like the paper) on Dropbox for Jonathan to edit, but when he makes edits I'll move them into the repo and commit them there.

Thoughts?

**Comment by drdeford** [comment]
This outline looks good to me. Best case scenario probably has something to do with minimizing the amount of duplication of data sources across the repos but there is obviously lots of potential overlap.

**Comment by nickeubank** [comment]
Yeah exactly. I think the only data duplication will be the ensembles, at least for the moment. Will get this up this afternoon so you can have access to voter points and kNN scores in `dislocation_and_simulated_districts` shortly!
