### ISSUE TITLE
Update on last run

### ISSUE THREAD

**Issue by nickeubank** [nickeubank/us_ensembles#17]
OK:

- Starting FL and CA. 
- three seeds were deemed invalid (runs 35, 41, 103). I'm *hoping* floating point error, and just bumped threshold to 0.021 (since each of those are one of three chains for a given state, seems unlikely it's a real systemic error). That means results are bad/not present for fips 17, run 2; fips 19 run 2; and fips 40 run 1. 
- All other results are being (very slowly) sync'd into dislocation_intermediate_files, and should be done and usable!

**Comment by nickeubank** [comment]
Oh, 42, 43, and 44 timed out so have to rerun those too (all three fips 20 runs).

**Comment by nickeubank** [comment]
Last note: Lots of states have only 1 US House district, so you'll find those folders empty.

**Comment by nickeubank** [comment]
The disk-management system bugs must be why the download of ensembles is running so slowly. Right now everything up to 35_run1 is done, but they're still coming down sequentially... hopefully it'll keep going overnight and we'll be done soon!

**Comment by nickeubank** [comment]
OK! Pulled everything ready. And other runs seem to have gotten started before they killed SLURM so, for the moment, they're running.

**Comment by nickeubank** [comment]
renamed folder `100_ensembles`.

**Comment by drdeford** [comment]
Great! Getting at least one run in each state is already an incredible achievement. I'll take a look at those seeds that failed too, floating point error is a possibility but in an ideal world the generation code would have caught that properly.

**Comment by nickeubank** [comment]
Isn't massive parallelism great? :)

OK -- all my jobs still seem to be running (or have completed), suggesting we escaped the SLURM triage. Also that does suggest that 0.021 worked and the issues was just floating point error:

```
queue(base) nce8@dcc-slogin-03  ~ $ squeue -u nce8
             JOBID PARTITION     NAME     USER ST       TIME  NODES NODELIST(REASON)
       14453294_42    common gerrycha     nce8  R 1-00:00:29      1 dcc-core-117
       14453294_43    common gerrycha     nce8  R 1-00:00:29      1 dcc-core-15
       14453294_44    common gerrycha     nce8  R 1-00:00:29      1 dcc-core-15
        14452284_9    common gerrycha     nce8  R 1-00:09:53      1 dcc-core-35
       14452284_10    common gerrycha     nce8  R 1-00:09:53      1 dcc-core-255
       14452284_11    common gerrycha     nce8  R 1-00:09:53      1 dcc-core-24
       14452284_24    common gerrycha     nce8  R 1-00:09:53      1 dcc-core-24
       14452284_25    common gerrycha     nce8  R 1-00:09:53      1 dcc-core-28
       14452284_26    common gerrycha     nce8  R 1-00:09:53      1 dcc-core-28
       14452284_35    common gerrycha     nce8  R 1-00:09:53      1 dcc-core-44
       14452284_41    common gerrycha     nce8  R 1-00:09:53      1 dcc-core-44
```

**Comment by nickeubank** [comment]
(presumably truncation during write out to JSON?)

**Comment by nickeubank** [comment]
ALL DONE! All sim runs in the dropbox folder ready for analysis!
