### ISSUE TITLE
Precinct / census merges

### ISSUE THREAD

**Issue by nickeubank** [nickeubank/us_ensembles#3]
So I've been ignoring precincts that don't merge with census blocks so long as they make up less than 0.5% of precincts in a state. This works for everyone but CA and... I think NY? 

In CA, the number is 0.9% (203 of 22205), about 40% of which are in LA. 

My inclination is to say <1% is good enough for this type of cross-country analysis. But I could write in the pro-rating trick to fix all of these. 

Thoughts?

**Comment by drdeford** [comment]
Are these precincts that don't have any census blocks that match to them? Because the block is larger than the precinct?

CA is a special kind of disaster for this because they have a really strict law about population balance for precincts that requires them to be redrawn constantly - it is a big part of why they aren't participating in the 2020 Census VTD program.

**Comment by nickeubank** [comment]
> Are these precincts that don't have any census blocks that match to them? Because the block is larger than the precinct?

I assume either bigger, or they aren't nested neatly, and a neighboring precinct had greater overlap so "claimed" all the people.

**Comment by nickeubank** [comment]
Also: this is only for Cali. Everyone else is under the 0.05% (save Montana, but something crazy's happening there I'll address).

**Comment by drdeford** [comment]
Hmmm... so the population will all be there but maybe missing the votes might skew things a little.   1% for CA seems reasonable to me, certainly well within the range of all the other possible sources of error here (including the underlying census data itself).

**Comment by nickeubank** [comment]
yup, exactly. 

OK, thanks. 

Now to figure out Montana, and move to ArcGIS for NY and FL. 

Soooo close...

**Comment by nickeubank** [comment]
sigh. no. I mean, the 1% with no census assignments is the tip of the iceberg -- it just speaks to general mis-alignments, and thus errors everywhere. 

Will implement the pro-rating...

**Comment by drdeford** [comment]
Gross! Precinct data really is the worst.

**Comment by nickeubank** [comment]
all done. a7f04eefc7deaa467b47a71bd66a6e0092dfa686
