### ISSUE TITLE
Test Timing Results

### ISSUE THREAD

**Issue by drdeford** [nickeubank/us_ensembles#4]
I tried out MI, AZ, and AR for 10k steps each, writing out data every 1k steps. The timing (to the extent that it is driven by the tree algorithm components) is really a function of (# Precincts / # Districts) since that determines the number of nodes in the merged districts that the trees are drawn on, so AR is actually the slowest (but also requires the fewest steps for the chain to mix). 

AZ took approximately 38 seconds per 100 plans,
MI took approximately 55 seconds per 100 plans,
and AR took around 108 seconds per 100 plans.

Times include I/O. I just removed one inefficient bit that was constructing one extra spanning tree per step :( so they should be a little quicker now together with bailing if ti draws more than 20 trees per merge (a short test shows AZ closer to 30 seconds per 100 but MI is pretty close to staying at 55). 

Extrapolating out to 100k, this looks like about 10-30 hours per ensemble with maybe 2-5GB output per state if I have multiplied properly. How does that match up with the available resources?

**Comment by nickeubank** [comment]
Perfect. Easily doable!

**Comment by drdeford** [comment]
Great! I set the run length to 100k in 20_run_simulation although we may want to test everything again first at 1k once all the states are together. I put the write to file interval at 1k steps, there is a tradeoff between RAM while running and general obnoxiousness of having many thousands of output files to process. If RAM isn't an issue, changing the write interval to 2k, 5k or even 10k might leave a more manageable set of outputs.

**Comment by nickeubank** [comment]
I can set ram requirements -- did you happen to see what ram is needed for 10K write intervals?

**Comment by nickeubank** [comment]
Running texas 1000 steps (and writing at the end) doesn't even come close to breaking a gig. So setting to write every 10K and asking system for 3gb ram per process just to be safe.
