### ISSUE TITLE
Montana (FIPS 30) won't convert itself into a graph, and I don't know why...

### ISSUE THREAD

**Issue by nickeubank** [nickeubank/us_ensembles#5]
OK, I think I've done everything up to simulations *except* I can't get the graph building code (`15_build_graph_parallel.py`) to work with Montana. I get the error: 

```
TopologyException: found non-noded intersection between LINESTRING (737130 9.10796e+06, 736749 9.10801e+06) and LINESTRING (736749 9.10801e+06, 736761 9.108e+06) at 736748.83119034348 9108005.4048477616
```

Which... I will admit I don't understand. 

Once you pull (will take a little while -- all my pre-processed maps uploaded) you should be able to play with it if that'd help?

**Comment by drdeford** [comment]
Sounds good, I'll take a stab at it in the morning. My guess is that some combination of buffering, snapping to a small gird, or deleting nodes from the linestring should take care of it - if necessary we can add the edge back in to the graph without too much trouble.

**Comment by drdeford** [comment]
Looks like there is some slightly crazy boundary stuff happening at that blue dot:
![MO_error](https://user-images.githubusercontent.com/29463610/71758196-d13bf500-2e6a-11ea-81f5-7c9f4cce3aa1.png)

Shouldn't be impossible to tweak it into reasonableness.

**Comment by drdeford** [comment]
Maybe easiest would just be to delete the little wedge polygon in QGIS. It has no votes and was awarded .07 people in population. The two real precincts will still touch on the western boundary, so the adjacency will be ok.

**Comment by nickeubank** [comment]
awesome, thanks -- I'll fix that!

**Comment by nickeubank** [comment]
damn... found another. I think there must be a bunch of these in this file. Whoever wrote it by hand must have made a mess:

```
TopologyException: found non-noded intersection between LINESTRING (611732 9.17267e+06, 611732 9.17267e+06) and LINESTRING (611732 9.17267e+06, 611732 9.17267e+06) at 611731.98776258528 9172671.8915124051
```

Hmmmm.... Will try throwing some simplify's at it.

**Comment by nickeubank** [comment]
or drop anything with sliver-sized areas.

**Comment by drdeford** [comment]
Yeah, that new one is a disaster: 
![MO2](https://user-images.githubusercontent.com/29463610/71768065-e9e6f200-2ee0-11ea-9c15-7633940ca744.png)

I hadn't really thought through the fact that it was crashing on the first instance it encountered.

**Comment by nickeubank** [comment]
Will turn to this if required: https://desktop.arcgis.com/en/arcmap/10.3/tools/data-management-toolbox/integrate.htm

But it's kinda dangerous...

**Comment by jrodden71** [comment]
Are you talking about precincts that are split into non-contiguous fragments?  If I remember correctly, this came up as an issue in court in FL.

**Comment by drdeford** [comment]
At least in Montana it just seems to be a problem of the boundaries not lining up nicely. I was able to build a dual graph for the original shapefile using shapely directly but it finds a bunch of ``islands'' and a whole host of other oddities: 
![MO_Dual2](https://user-images.githubusercontent.com/29463610/71768903-de97c480-2ee8-11ea-9a2c-4af20e660eb0.png)

**Comment by nickeubank** [comment]
Yup. Just turned to `Integrate` in Arc, re-running code now...

**Comment by nickeubank** [comment]
Integrate definitely created a few issues -- some precincts that have identical boundaries. But it's only about 2.5% , and I think we can just drop Montana if we have to...

gonna see if I can get a graph out of it...

**Comment by nickeubank** [comment]
OK, that works. Phew. :)
