### ISSUE TITLE
Florida seed won't converge

### ISSUE THREAD

**Issue by nickeubank** [nickeubank/us_ensembles#6]
So the "build a new seed" code won't stop running for FL. Should I widen the population constraint? Or is that a sign of a problem?

**Comment by drdeford** [comment]
It might be a weird contiguity issue. Can you save the dual graph before it tries to grow the new seed?

**Comment by nickeubank** [comment]
yup, give me a minute...

**Comment by nickeubank** [comment]
[precinct_graphs_12_PRESEED.json.zip](https://github.com/nickeubank/us_ensembles/files/4022097/precinct_graphs_12_PRESEED.json.zip)

**Comment by drdeford** [comment]
Thanks! Will take a look.

**Comment by drdeford** [comment]
I wonder if the island code is adding too many edges around the everglades: 
![FL_whole](https://user-images.githubusercontent.com/29463610/71768237-56aebc00-2ee2-11ea-96cc-822009ae1158.png)
![FL_zoom](https://user-images.githubusercontent.com/29463610/71768239-5a424300-2ee2-11ea-83ae-04c14ecd9055.png)

I've gotten it to build plans with up to 15 districts at the 2% population balance level but am stumbling at 20. At 5% I was able to make a full plan of 27 districts in just a few seconds.

**Comment by nickeubank** [comment]
jesus. ok, yeah, let me cap the connection limit for FL.

**Comment by nickeubank** [comment]
capped at 5 connections, running now.

**Comment by drdeford** [comment]
I'll take a pass through all of the state plots to see if anything else stick out.

**Comment by nickeubank** [comment]
Here's an updated map where I limit connections to fix gaps to max of 5.  Still not converging. Look at better graphically?

[precinct_graphs_12_PRESEED.json.zip](https://github.com/nickeubank/us_ensembles/files/4022198/precinct_graphs_12_PRESEED.json.zip)

**Comment by nickeubank** [comment]
(we could also just drop FL. Given our study context, it wouldn't be the end of the world to drop a state or two)

**Comment by drdeford** [comment]
Still a little crazy: 
![FL2](https://user-images.githubusercontent.com/29463610/71769239-692df300-2eec-11ea-83a5-07bb51de5eab.png)

I wonder if these are a couple of the discontiguous precincts that Jonathan mentioned. Sure enough, this appears to be one precinct: 
![FL_precinct](https://user-images.githubusercontent.com/29463610/71769283-199bf700-2eed-11ea-848d-46b13f675f8d.png)

**Comment by nickeubank** [comment]
aha.... well...

thoughts? Delete all components but that big one?

@jrodden71 any idea what's going on there?

**Comment by drdeford** [comment]
I would worry that that might disconnect some of the smaller pieces inside. Maybe  we could try one of the looser constrained seeds and use the proposal to tighten it?

I uploaded plots of the rest of the initial seeds here: https://github.com/nickeubank/us_ensembles/tree/master/20_intermediate_files/initial_seed_plots 

At a quick glance they seem to pass the eyeball test.

**Comment by nickeubank** [comment]
Still won't get seeds at 5% threshold. Trying 10%.

**Comment by nickeubank** [comment]
10% won't seed! WTF?

**Comment by drdeford** [comment]
I have been able to build some 5% ones locally but they are slow. Will upload when all three are done.

**Comment by nickeubank** [comment]
YES. OK, thanks. Maybe I was just impatient. I'll re-start CA (#8 ) and be more patient.

**Comment by drdeford** [comment]
[floridacontainer.zip](https://github.com/nickeubank/us_ensembles/files/4022348/floridacontainer.zip)

Here are 3 Florida 5% seeds. Those discontiguous precincts in the south lead to some ugly looking districts but I'm not sure what to do about it except delete...

**Comment by nickeubank** [comment]
thanks, adding to repo!
